---
version: '3.7'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
  server:
    build:
      context: './'
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/graphql-development
      - PORT=4000
